name: images

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push jdk17
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jdk17
        tags: |
          ghcr.io/turbokube/jdk17:latest
          ghcr.io/turbokube/jdk17:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push jre17
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jre17
        tags: |
          ghcr.io/turbokube/jre17:latest
          ghcr.io/turbokube/jre17:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push jre17-watch
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jre17-watch
        tags: |
          ghcr.io/turbokube/jre17-watch:latest
          ghcr.io/turbokube/jre17-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push nodejs-watchexec
      uses: docker/build-push-action@v4
      with:
        context: .
        target: nodejs-watchexec
        tags: |
          ghcr.io/turbokube/nodejs-watchexec:latest
          ghcr.io/turbokube/nodejs-watchexec:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push static-watch
      uses: docker/build-push-action@v4
      with:
        context: .
        target: static-watch
        tags: |
          ghcr.io/turbokube/static-watch:latest
          ghcr.io/turbokube/static-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
