name: images

on:
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push jdk21
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jdk21
        tags: |
          ghcr.io/turbokube/jdk21:latest
          ghcr.io/turbokube/jdk21:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push jre21
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jre21
        tags: |
          ghcr.io/turbokube/jre21:latest
          ghcr.io/turbokube/jre21:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push jre21-watch
      uses: docker/build-push-action@v4
      with:
        context: .
        target: jre21-watch
        tags: |
          ghcr.io/turbokube/jre21-watch:latest
          ghcr.io/turbokube/jre21-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push nodejs
      uses: docker/build-push-action@v4
      with:
        context: .
        target: nodejs
        tags: |
          ghcr.io/turbokube/nodejs:latest
          ghcr.io/turbokube/nodejs:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push nodejs-watch
      uses: docker/build-push-action@v4
      with:
        context: .
        target: nodejs-watch
        tags: |
          ghcr.io/turbokube/nodejs-watch:latest
          ghcr.io/turbokube/nodejs-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Build and push static-watch
      uses: docker/build-push-action@v4
      with:
        context: .
        target: static-watch
        tags: |
          ghcr.io/turbokube/static-watch:latest
          ghcr.io/turbokube/static-watch:${{ github.sha }}
        platforms: linux/amd64,linux/arm64
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
